// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RESTAPI.Migrations
{
    [DbContext(typeof(RESTAPIContext))]
    [Migration("20260605225424_pageImageotm")]
    partial class pageImageotm
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RESTAPI.Models.GameDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("genreid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("genreid");

                    b.ToTable("gamedescription", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("genrename")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("genre", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Locationid")
                        .HasColumnType("integer");

                    b.Property<int?>("TheoryPagesid")
                        .HasColumnType("integer");

                    b.Property<int?>("pageid")
                        .HasColumnType("integer");

                    b.Property<int?>("theoryid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Locationid");

                    b.HasIndex("TheoryPagesid");

                    b.HasIndex("pageid");

                    b.ToTable("image", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TheoryPagesid")
                        .HasColumnType("integer");

                    b.Property<string>("buttonX")
                        .HasColumnType("text");

                    b.Property<string>("buttonY")
                        .HasColumnType("text");

                    b.Property<int?>("genreid")
                        .HasColumnType("integer");

                    b.Property<int?>("pageid")
                        .HasColumnType("integer");

                    b.Property<int?>("theoryId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("TheoryPagesid");

                    b.HasIndex("genreid");

                    b.HasIndex("pageid")
                        .IsUnique();

                    b.ToTable("Location", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PageDescription")
                        .HasColumnType("text");

                    b.Property<string>("PageTitle")
                        .HasColumnType("text");

                    b.Property<int>("genreid")
                        .HasColumnType("integer");

                    b.Property<Guid>("userid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("genreid");

                    b.HasIndex("userid");

                    b.ToTable("pages", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Practice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("pageid")
                        .HasColumnType("integer");

                    b.Property<int>("practicetype")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("pageid");

                    b.ToTable("practice", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.TheoryPages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imageurl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("theorypages", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("pageid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("pageid");

                    b.ToTable("vote", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.GameDescription", b =>
                {
                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("RESTAPI.Models.Image", b =>
                {
                    b.HasOne("RESTAPI.Models.Location", null)
                        .WithMany("images")
                        .HasForeignKey("Locationid");

                    b.HasOne("RESTAPI.Models.TheoryPages", "TheoryPages")
                        .WithMany()
                        .HasForeignKey("TheoryPagesid");

                    b.HasOne("RESTAPI.Models.Page", "pages")
                        .WithMany("images")
                        .HasForeignKey("pageid");

                    b.Navigation("TheoryPages");

                    b.Navigation("pages");
                });

            modelBuilder.Entity("RESTAPI.Models.Location", b =>
                {
                    b.HasOne("RESTAPI.Models.TheoryPages", null)
                        .WithMany("location")
                        .HasForeignKey("TheoryPagesid");

                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid");

                    b.HasOne("RESTAPI.Models.Page", "Page")
                        .WithOne("location")
                        .HasForeignKey("RESTAPI.Models.Location", "pageid");

                    b.Navigation("Genre");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RESTAPI.Models.Page", b =>
                {
                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RESTAPI.Models.Practice", b =>
                {
                    b.HasOne("RESTAPI.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("pageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RESTAPI.Models.Vote", b =>
                {
                    b.HasOne("RESTAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAPI.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("pageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RESTAPI.Models.Location", b =>
                {
                    b.Navigation("images");
                });

            modelBuilder.Entity("RESTAPI.Models.Page", b =>
                {
                    b.Navigation("images");

                    b.Navigation("location");
                });

            modelBuilder.Entity("RESTAPI.Models.TheoryPages", b =>
                {
                    b.Navigation("location");
                });
#pragma warning restore 612, 618
        }
    }
}
