// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RESTAPI.Migrations
{
    [DbContext(typeof(RESTAPIContext))]
    partial class RESTAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RESTAPI.Models.GameDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("genreid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("genreid");

                    b.ToTable("gamedescription", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Genre", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("genrename")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("genre", "public");

                    b.HasData(
                        new
                        {
                            id = 1,
                            genrename = "Adventure"
                        },
                        new
                        {
                            id = 2,
                            genrename = "Puzzle"
                        },
                        new
                        {
                            id = 3,
                            genrename = "Racing"
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.Location", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("genreid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("genreid");

                    b.ToTable("Location", "public");

                    b.HasData(
                        new
                        {
                            id = 1,
                            RegionDescription = "World exploration and quests",
                            RegionName = "Adventure Region",
                            genreid = 1
                        },
                        new
                        {
                            id = 2,
                            RegionDescription = "Logic challenges",
                            RegionName = "Puzzle Region",
                            genreid = 2
                        },
                        new
                        {
                            id = 3,
                            RegionDescription = "Speed and competition",
                            RegionName = "Racing Region",
                            genreid = 3
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.Page", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PageDescription")
                        .HasColumnType("text");

                    b.Property<string>("PageTitle")
                        .HasColumnType("text");

                    b.Property<int>("genreid")
                        .HasColumnType("integer");

                    b.Property<Guid>("userid")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("genreid");

                    b.HasIndex("userid");

                    b.ToTable("pages", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.Practice", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("pageid")
                        .HasColumnType("integer");

                    b.Property<int>("practicetype")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("pageid");

                    b.ToTable("practice", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.TheoryPages", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("imageurl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("theorypages", "public");

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "Understanding movement in games",
                            imageurl = "http://10.0.2.2:5035/images/WTTTTTTTF.png",
                            title = "Physics Basics"
                        },
                        new
                        {
                            id = 2,
                            description = "How game AI reacts to players",
                            imageurl = "http://10.0.2.2:5035/images/WTTTTTTTF.png",
                            title = "AI Behavior"
                        },
                        new
                        {
                            id = 3,
                            description = "Designing engaging game levels",
                            imageurl = "http://10.0.2.2:5035/images/WTTTTTTTF.png",
                            title = "Level Design"
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Password = "$2a$11$hash_admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            Password = "$2a$11$hash_player1",
                            Username = "player1"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Password = "$2a$11$hash_tester",
                            Username = "tester"
                        });
                });

            modelBuilder.Entity("RESTAPI.Models.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("pageid")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("pageid");

                    b.ToTable("vote", "public");
                });

            modelBuilder.Entity("RESTAPI.Models.GameDescription", b =>
                {
                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("RESTAPI.Models.Location", b =>
                {
                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("RESTAPI.Models.Page", b =>
                {
                    b.HasOne("RESTAPI.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("genreid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RESTAPI.Models.Practice", b =>
                {
                    b.HasOne("RESTAPI.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("pageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");
                });

            modelBuilder.Entity("RESTAPI.Models.Vote", b =>
                {
                    b.HasOne("RESTAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RESTAPI.Models.Page", "Page")
                        .WithMany()
                        .HasForeignKey("pageid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Page");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
